project:
  type: website
  output-dir: "docs"

website:
  title: "Satoshi Matsumoto"
  navbar:
    left: 
      - text: "Home"
        file: index.qmd
      - text: "Portfolio"
        file: portfolio.qmd
      - text: "Blog"
        file: blog.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/satoshi-F13
      - icon: mastodon
        href: https://mastodon.social/@satoshi_F13
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css

editor: visual

